# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-23 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0038_turno_si'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'permissions': (('finish_turno', 'Can finish turno'), ('cancel_turno', 'Can cancel turno'), ('add_turno_LIM1', 'Can add turno LIM1'), ('add_turno_LIM2', 'Can add turno LIM2'), ('add_turno_LIM3', 'Can add turno LIM3'), ('add_turno_LIM4', 'Can add turno LIM4'), ('add_turno_LIM5', 'Can add turno LIM5'), ('add_turno_LIM6', 'Can add turno LIM6'), ('add_turno_LIA', 'Can add turno LIA'), ('add_turno_EXT', 'Can add turno EXT'), ('add_turno_TICS', 'Can add turno TICS'), ('add_turno_DES', 'Can add turno DES'), ('add_turno_CAL', 'Can add turno CAL'), ('add_turno_MEC', 'Can add turno MEC'), ('add_turno_ML', 'Can add turno ML'), ('change_turno_LIM1', 'Can change turno LIM1'), ('change_turno_LIM2', 'Can change turno LIM2'), ('change_turno_LIM3', 'Can change turno LIM3'), ('change_turno_LIM4', 'Can change turno LIM4'), ('change_turno_LIM5', 'Can change turno LIM5'), ('change_turno_LIM6', 'Can change turno LIM6'), ('change_turno_LIA', 'Can change turno LIA'), ('change_turno_EXT', 'Can change turno EXT'), ('change_turno_TICS', 'Can change turno TICS'), ('change_turno_DES', 'Can change turno DES'), ('change_turno_CAL', 'Can change turno CAL'), ('change_turno_MEC', 'Can change turno MEC'), ('change_turno_ML', 'Can change turno ML'), ('delete_turno_LIM1', 'Can delete turno LIM1'), ('delete_turno_LIM2', 'Can delete turno LIM2'), ('delete_turno_LIM3', 'Can delete turno LIM3'), ('delete_turno_LIM4', 'Can delete turno LIM4'), ('delete_turno_LIM5', 'Can delete turno LIM5'), ('delete_turno_LIM6', 'Can delete turno LIM6'), ('delete_turno_LIA', 'Can delete turno LIA'), ('delete_turno_EXT', 'Can delete turno EXT'), ('delete_turno_TICS', 'Can delete turno TICS'), ('delete_turno_DES', 'Can delete turno DES'), ('delete_turno_CAL', 'Can delete turno CAL'), ('delete_turno_MEC', 'Can delete turno MEC'), ('delete_turno_ML', 'Can delete turno ML'), ('finish_turno_LIM1', 'Can finish turno LIM1'), ('finish_turno_LIM2', 'Can finish turno LIM2'), ('finish_turno_LIM3', 'Can finish turno LIM3'), ('finish_turno_LIM4', 'Can finish turno LIM4'), ('finish_turno_LIM5', 'Can finish turno LIM5'), ('finish_turno_LIM6', 'Can finish turno LIM6'), ('finish_turno_LIA', 'Can finish turno LIA'), ('finish_turno_EXT', 'Can finish turno EXT'), ('finish_turno_TICS', 'Can finish turno TICS'), ('finish_turno_DES', 'Can finish turno DES'), ('finish_turno_CAL', 'Can finish turno CAL'), ('finish_turno_MEC', 'Can finish turno MEC'), ('finish_turno_ML', 'Can finish turno ML'), ('cancel_turno_LIM1', 'Can cancel turno LIM1'), ('cancel_turno_LIM2', 'Can cancel turno LIM2'), ('cancel_turno_LIM3', 'Can cancel turno LIM3'), ('cancel_turno_LIM4', 'Can cancel turno LIM4'), ('cancel_turno_LIM5', 'Can cancel turno LIM5'), ('cancel_turno_LIM6', 'Can cancel turno LIM6'), ('cancel_turno_LIA', 'Can cancel turno LIA'), ('cancel_turno_EXT', 'Can cancel turno EXT'), ('cancel_turno_TICS', 'Can cancel turno TICS'), ('cancel_turno_DES', 'Can cancel turno DES'), ('cancel_turno_CAL', 'Can cancel turno CAL'), ('cancel_turno_MEC', 'Can cancel turno MEC'), ('cancel_turno_ML', 'Can cancel turno ML'))},
        ),
        migrations.AlterField(
            model_name='turno',
            name='area',
            field=models.CharField(choices=[(b'LIA', b'LIA'), (b'LIM1', b'LIM1'), (b'LIM2', b'LIM2'), (b'LIM3', b'LIM3'), (b'LIM4', b'LIM4'), (b'LIM5', b'LIM5'), (b'LIM6', b'LIM6'), (b'EXT', b'EXT'), (b'TICS', b'TICS'), (b'DES', b'DES'), (b'CAL', b'CAL'), (b'MEC', b'MEC'), (b'ML', b'ML')], max_length=10),
        ),
    ]
