# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-26 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0183_ofertatec_descripcion'),
        ('lab', '0039_auto_20180823_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertatec_linea',
            name='ofertatec_old',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adm.OfertaTec_Descripcion', verbose_name=b'OfertaTec Centro'),
        ),
    ]
