# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-27 17:38
from __future__ import unicode_literals

import adm.models
import audit_log.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adm', '0158_auto_20171124_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('contribucion', models.BooleanField(default=False, verbose_name=b'Contribuci\xc3\xb3n')),
                ('anio', models.CharField(choices=[(b'2017', b'2017'), (b'2018', b'2018'), (b'2019', b'2019')], default=adm.models.yearNow, max_length=4, verbose_name=b'A\xc3\xb1o')),
                ('tipo', models.CharField(choices=[(b'POA', b'POA'), (b'PDI', b'PDI')], max_length=3, verbose_name=b'Tipo de Plan')),
                ('nombre', models.CharField(max_length=500, verbose_name=b'Nombre')),
                ('codigo', models.CharField(error_messages={b'unique': b'C\xc3\xb3digo duplicado.'}, max_length=5, unique=True, verbose_name=b'C\xc3\xb3digo')),
                ('cantidad_servicios', models.PositiveIntegerField(default=0, verbose_name=b'Cantidad de Servicios')),
                ('cantidad_contratos', models.PositiveIntegerField(default=0, verbose_name=b'Cantidad de OT/SOT/RUT Anuales')),
                ('facturacion_prevista', models.FloatField(default=0, verbose_name=b'Facturaci\xc3\xb3n Anual Prevista por OT')),
                ('generacion_neta', models.FloatField(default=0, verbose_name=b'Generaci\xc3\xb3n Neta')),
                ('agentes', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('created_by', audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_adm_pdt_set', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_adm_pdt_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'ordering': ['anio', 'codigo'],
            },
        ),
        migrations.AddField(
            model_name='ot',
            name='pdt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adm.PDT', verbose_name=b'PDT'),
        ),
        migrations.AddField(
            model_name='otml',
            name='pdt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adm.PDT', verbose_name=b'PDT'),
        ),
        migrations.AddField(
            model_name='rut',
            name='pdt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adm.PDT', verbose_name=b'PDT'),
        ),
        migrations.AddField(
            model_name='si',
            name='pdt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adm.PDT', verbose_name=b'PDT'),
        ),
        migrations.AddField(
            model_name='sot',
            name='pdt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adm.PDT', verbose_name=b'PDT'),
        ),
    ]
