# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-28 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0162_auto_20171227_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ot',
            name='pdt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm.PDT', verbose_name=b'PDT'),
        ),
        migrations.AlterField(
            model_name='otml',
            name='pdt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm.PDT', verbose_name=b'PDT'),
        ),
        migrations.AlterField(
            model_name='rut',
            name='pdt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm.PDT', verbose_name=b'PDT'),
        ),
        migrations.AlterField(
            model_name='si',
            name='pdt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm.PDT', verbose_name=b'PDT'),
        ),
        migrations.AlterField(
            model_name='sot',
            name='pdt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adm.PDT', verbose_name=b'PDT'),
        ),
    ]
