# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-03 14:00
from __future__ import unicode_literals

import adm.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0164_auto_20171228_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='pdt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adm.PDT', verbose_name=b'PDT'),
        ),
        migrations.AlterField(
            model_name='pdt',
            name='anio',
            field=models.CharField(choices=[(b'2017', b'2017'), (b'2018', b'2018'), (b'2019', b'2019'), (b'2020', b'2020')], default=adm.models.yearNow, max_length=4, verbose_name=b'A\xc3\xb1o'),
        ),
    ]
