# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-24 16:19
from __future__ import unicode_literals

import adm.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0170_auto_20180426_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presupuesto',
            options={'ordering': ['-codigo'], 'permissions': (('finish_presupuesto', 'Can finish presupuesto'), ('cancel_presupuesto', 'Can cancel presupuesto'), ('read_presupuesto', 'Can read presupuesto'))},
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='nro_presea',
            field=models.CharField(default=b'0000-00000000', error_messages={b'unique': b'Ya existe un presupuesto con ese n\xc3\xbamero.'}, max_length=13, validators=[django.core.validators.RegexValidator(b'^\\d{4}-\\d{8}$', message=b'El c\xc3\xb3digo debe ser de la forma 0000-00000000')], verbose_name=b'Nro. Presea'),
        ),
        migrations.AlterField(
            model_name='pdt',
            name='anio',
            field=models.CharField(choices=[(b'2017', b'2017'), (b'2018', b'2018'), (b'2019', b'2019'), (b'2020', b'2020'), (b'2021', b'2021')], default=adm.models.yearNow, max_length=4, null=True, verbose_name=b'A\xc3\xb1o'),
        ),
    ]
