# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-13 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('adm', '0170_auto_20180426_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presupuesto',
            options={'ordering': ['-codigo'], 'permissions': (('finish_presupuesto', 'Can finish presupuesto'), ('cancel_presupuesto', 'Can cancel presupuesto'), ('read_presupuesto', 'Can read presupuesto'))},
        ),
        migrations.AddField(
            model_name='remito',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='remito',
            name='informe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='remito',
            name='instrumento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='remito',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
