# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-23 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0170_auto_20180426_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presupuesto',
            options={'ordering': ['-codigo'], 'permissions': (('finish_presupuesto', 'Can finish presupuesto'), ('cancel_presupuesto', 'Can cancel presupuesto'), ('read_presupuesto', 'Can read presupuesto'))},
        ),
        migrations.AlterField(
            model_name='rut',
            name='solicitante',
            field=models.CharField(choices=[(b'LIA', b'LIA'), (b'LIM1', b'LIM1'), (b'LIM2', b'LIM2'), (b'LIM3', b'LIM3'), (b'LIM4', b'LIM4'), (b'LIM5', b'LIM5'), (b'LIM6', b'LIM6'), (b'EXT', b'EXT'), (b'TICS', b'TICS'), (b'DES', b'DES'), (b'CAL', b'CAL'), (b'MEC', b'MEC'), (b'ML', b'ML')], max_length=4, verbose_name=b'Area Solicitante'),
        ),
        migrations.AlterField(
            model_name='si',
            name='ejecutor',
            field=models.CharField(choices=[(b'LIA', b'LIA'), (b'LIM1', b'LIM1'), (b'LIM2', b'LIM2'), (b'LIM3', b'LIM3'), (b'LIM4', b'LIM4'), (b'LIM5', b'LIM5'), (b'LIM6', b'LIM6'), (b'EXT', b'EXT'), (b'TICS', b'TICS'), (b'DES', b'DES'), (b'CAL', b'CAL'), (b'MEC', b'MEC'), (b'ML', b'ML')], max_length=4, verbose_name=b'UT Ejecutora'),
        ),
        migrations.AlterField(
            model_name='si',
            name='solicitante',
            field=models.CharField(choices=[(b'LIA', b'LIA'), (b'LIM1', b'LIM1'), (b'LIM2', b'LIM2'), (b'LIM3', b'LIM3'), (b'LIM4', b'LIM4'), (b'LIM5', b'LIM5'), (b'LIM6', b'LIM6'), (b'EXT', b'EXT'), (b'TICS', b'TICS'), (b'DES', b'DES'), (b'CAL', b'CAL'), (b'MEC', b'MEC'), (b'ML', b'ML')], max_length=4, verbose_name=b'UT Solicitante'),
        ),
        migrations.AlterField(
            model_name='sot',
            name='solicitante',
            field=models.CharField(choices=[(b'LIA', b'LIA'), (b'LIM1', b'LIM1'), (b'LIM2', b'LIM2'), (b'LIM3', b'LIM3'), (b'LIM4', b'LIM4'), (b'LIM5', b'LIM5'), (b'LIM6', b'LIM6'), (b'EXT', b'EXT'), (b'TICS', b'TICS'), (b'DES', b'DES'), (b'CAL', b'CAL'), (b'MEC', b'MEC'), (b'ML', b'ML')], max_length=4, verbose_name=b'Area Solicitante'),
        ),
    ]
