# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-16 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0172_auto_20180716_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remito',
            name='ot',
        ),
        migrations.AlterField(
            model_name='remito',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='remito',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
