# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-23 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0171_auto_20180823_1018'),
        ('adm', '0173_auto_20180716_1415'),
    ]

    operations = [
    ]
