# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-09 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0175_auto_20180806_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adm.Contacto', verbose_name=b'Contacto'),
        ),
    ]
