# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-23 13:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0177_auto_20180816_0900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='direccionusuario',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='contacto',
            name='mail',
            field=models.CharField(max_length=250, validators=[django.core.validators.EmailValidator(message=b'Ingrese un email v\xc3\xa1lido.')], verbose_name=b'Mail'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(b"^([A-Za-z]|[\xc3\xa1\xc3\xa9\xc3\xad\xc3\xb3\xc3\xba]|[ \\'])*$", b'Solo se permiten caracteres alfab\xc3\xa9ticos.')], verbose_name=b'Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='mail',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.EmailValidator(message=b'Ingrese un email v\xc3\xa1lido.')], verbose_name=b'Mail'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(error_messages={b'unique': b'Ya existe un usuario con ese nombre.'}, max_length=150, unique=True, verbose_name=b'Raz\xc3\xb3n Social'),
        ),
    ]
