# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-11 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0179_auto_20180831_1423'),
        ('adm', '0174_merge'),
    ]

    operations = [
    ]
