# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-08 12:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0182_auto_20190425_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ot',
            name='codigo',
            field=models.CharField(default=b'00216-00000000', error_messages={b'unique': b'Ya existe una OT con ese n\xc3\xbamero.'}, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(b'^\\d{5}-\\d{8}$|^\\d{5}-\\d{8}\\/\\d{2}$', message=b'El c\xc3\xb3digo debe ser de la forma 00000-00000000 \xc3\xb3 00000-00000000/00')], verbose_name=b'Nro. OT'),
        ),
        migrations.AlterField(
            model_name='otml',
            name='codigo',
            field=models.CharField(default=b'00307-00000000', error_messages={b'unique': b'Ya existe una OT con ese n\xc3\xbamero.'}, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(b'^\\d{5}-\\d{8}$|^\\d{5}-\\d{8}\\/\\d{2}$', message=b'El c\xc3\xb3digo debe ser de la forma 00000-00000000 \xc3\xb3 00000-00000000/00')], verbose_name=b'Nro. OT'),
        ),
    ]
