# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-26 12:08
from __future__ import unicode_literals

import audit_log.models.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adm', '0182_auto_20190425_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaTec_Descripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('codigo', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(b'^\\d{14}$')], verbose_name=b'C\xc3\xb3digo')),
                ('detalle', models.CharField(max_length=350, verbose_name=b'Detalle')),
                ('created_by', audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_adm_ofertatec_descripcion_set', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_adm_ofertatec_descripcion_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
    ]
