# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-08 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0183_auto_20190508_0929'),
        ('adm', '0184_ot_linea_ofertatec_old'),
    ]

    operations = [
    ]
