# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-14 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0186_auto_20190610_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdt',
            options={'ordering': ['-anio', 'codigo'], 'permissions': (('read_pdt', 'Can read pdt'),)},
        ),
    ]
