# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-14 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0187_auto_20190614_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroDeCostos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, verbose_name=b'C\xc3\xb3digo')),
                ('nombre', models.CharField(max_length=100, verbose_name=b'Centro de Costo')),
                ('tipo', models.CharField(choices=[(b'Presidencia', b'Presidencia'), (b'Vicepresidencia', b'Vicepresidencia'), (b'CD', b'Consejo Directivo'), (b'Unidad', b'Unidad'), (b'Direcci\xc3\xb3n', b'Direcci\xc3\xb3n'), (b'GO', b'Gerencia Operativa'), (b'SO', b'Subgerencia Operativa'), (b'DT', b'Direcic\xc3\xb3n T\xc3\xa9cnica'), (b'DEPTO', b'Departamento'), (b'Otros', b'Otros')], max_length=15, verbose_name=b'Tipo de CC')),
                ('region', models.CharField(choices=[(b'PTM', b'PTM'), (b'CENTRO', b'CENTRO'), (b'CUYO', b'CUYO'), (b'NEA', b'NEA'), (b'NOA', b'NOA'), (b'PAMPEANA', b'PAMPEANA'), (b'PATAGONIA', b'PATAGONIA'), (b'BUENOS AIRES', b'BUENOS AIRES')], max_length=12, verbose_name=b'Regi\xc3\xb3n')),
            ],
            options={
                'ordering': ['-codigo'],
            },
        ),
    ]
