# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-14 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0188_centrodecostos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrodecostos',
            name='tipo',
            field=models.CharField(choices=[(b'Presidencia', b'Presidencia'), (b'Vicepresidencia', b'Vicepresidencia'), (b'CD', b'Consejo Directivo'), (b'Unidad', b'Unidad'), (b'Direcci\xc3\xb3n', b'Direcci\xc3\xb3n'), (b'GO', b'Gerencia Operativa'), (b'SO', b'Subgerencia Operativa'), (b'DT', b'Direcci\xc3\xb3n T\xc3\xa9cnica'), (b'DEPTO', b'Departamento'), (b'Otros', b'Otros')], max_length=21, verbose_name=b'Tipo de CC'),
        ),
    ]
