# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-18 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0189_auto_20190614_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaTematica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name=b'Area Tem\xc3\xa1tica')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
