# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-09 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Fecha')),
                ('activity', models.CharField(max_length=500, verbose_name='Actividad')),
                ('comments', models.CharField(max_length=800, verbose_name='Observaciones')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Modelo')),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
    ]
