# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-10 17:06
from __future__ import unicode_literals

import audit_log.models.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='created_by',
            field=audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_activity_log_activitylog_set', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='created_with_session_key',
            field=audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='modified_by',
            field=audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_activity_log_activitylog_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='modified_with_session_key',
            field=audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True),
        ),
    ]
